### ISSUE TITLE
Can't create Table cm_sms_message with recommended symfony character setting

### ISSUE THREAD

**Issue by sral97** [endroid/cm-sms-bundle#1]
When setting the database encoding to utf8mb4 as recommended by the symfony cookbook [here](http://symfony.com/doc/3.4/doctrine.html), the database (MariaDB 10.1.26) throws following error: `#1071 - Specified key was too long; max key length is 767 bytes`. 

This is clearly because utf8mb4 needs 4 bytes per character and therefore VARCHAR(255) in the generated insert statement exceeds the maximum key length.

How should one go about this?

**Comment by endroid** [comment]
Hi @sral97 this is not really related to this library but I found the following post regarding the issue.

https://github.com/gogits/gogs/issues/4894

According to that post you should either update MariaDB to a more recent version or use the ALTER TABLE _tablename_ ROW_FORMAT=DYNAMIC command.
