### ISSUE TITLE
Sending test messages fails because sender is empty.

### ISSUE THREAD

**Issue by sral97** [endroid/cm-sms-bundle#2]
When sending test messages using the provided interface, it always fails. I traced the error to being located in `Endroid\CmSms\Client` inside `createMessagesJson`. In line 119 there is an `is_null($message->getFrom())` check, but the from field is set to an empty string when i dump the contents just before the check.

Symfony Version: 4.0.4
PHP Version 7.2.2

**Comment by endroid** [comment]
You're right. The getFrom() message always returns a string, never not null given its method signature. So the check should indeed be different. Now I check if the returned value is an empty string so it uses the default when the value is empty.
